// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

int duration;
int frequency;

void initProperties(){

  ArduinoCloud.addProperty(duration, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(frequency, READWRITE, ON_CHANGE);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);